# NET core (cpunet) Bluetooth Controller image (HCI over IPC)

CONFIG_IPC_SERVICE=y
CONFIG_MBOX=y

CONFIG_MAIN_STACK_SIZE=512
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=512
CONFIG_HEAP_MEM_POOL_SIZE=4096

CONFIG_BT=y
CONFIG_BT_CTLR=y

# SoftDevice Controller on the netcore
CONFIG_BT_LL_SOFTDEVICE=y

# Controller exposes HCI to cpuapp via IPC
CONFIG_BT_HCI_RAW=y

# Keep netcore quiet (optional)
CONFIG_LOG=n
CONFIG_CONSOLE=n
CONFIG_PRINTK=n
